config/routes.rb
Rails.application.routes.draw do
  resources :website, only: :index
  resources :projects, only: :index
  resources :interests, only: :index
  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController

  def index

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/interests/index.html.erb
index.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%#= render 'shared/navigation' %>
      <div id="main-container" class="container">
        <div class="row">
          <div class="col-xs-3"></div>
            <div class="col-xs-9">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
</body>
</html>

app/views/projects/index.html.erb
index.html.erb

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Becca Ades</a>
    </div>
  </div>
</nav>

app/views/website/index.html.erb
<%= render 'shared/navigation' %>
<h1>Who are you anyway?</h1>
<p>All About Me!</p>

<h1><%= link_to "http://beccaades.github.io/", class: 'btn btn-success' do %>
      <i class="glyphicons glyphicons-pencil"></i> Learn it. Blog it.
    <% end %>
</h1>


<h1><%= link_to projects_path, class: 'btn btn-success' do %>
      <i class='fa fa-diamond'></i> Projects
    <% end %>
</h1>
<h1><%= link_to "Interests", interests_path, class: 'btn btn-success' %></h1>

app/views/welcome/index.html.erb
    <link rel="stylesheets" href="../../assets/stylesheets/doc.css"> 
    <script type="text/javascript" src="js/paper-full.js"></script>
    <script type="text/paperscript" canvas="canvas">
        // Code ported to Paper.js from http://the389.com/9/1/
        // with permission.
        var values = {
            friction: 0.8,
            timeStep: 0.01,
            amount: 15,
            mass: 2,
            count: 0
        };
        values.invMass = 1 / values.mass;

        var path, springs;
        var size = view.size * [1.2, 1];

        var Spring = function(a, b, strength, restLength) {
            this.a = a;
            this.b = b;
            this.restLength = restLength || 80;
            this.strength = strength ? strength : 0.55;
            this.mamb = values.invMass * values.invMass;
        };

        Spring.prototype.update = function() {
            var delta = this.b - this.a;
            var dist = delta.length;
            var normDistStrength = (dist - this.restLength) /
                    (dist * this.mamb) * this.strength;
            delta.y *= normDistStrength * values.invMass * 0.2;
            if (!this.a.fixed)
                this.a.y += delta.y;
            if (!this.b.fixed)
                this.b.y -= delta.y;
        };


        function createPath(strength) {
            var path = new Path({
                fillColor: 'black'
            });
            springs = [];
            for (var i = 0; i <= values.amount; i++) {
                var segment = path.add(new Point(i / values.amount, 0.5) * size);
                var point = segment.point;
                if (i == 0 || i == values.amount)
                    point.y += size.height;
                point.px = point.x;
                point.py = point.y;
                // The first two and last two points are fixed:
                point.fixed = i < 2 || i > values.amount - 2;
                if (i > 0) {
                    var spring = new Spring(segment.previous.point, point, strength);
                    springs.push(spring);
                }
            }
            path.position.x -= size.width / 4;
            return path;
        }

        function onResize() {
            if (path)
                path.remove();
            size = view.bounds.size * [2, 1];
            path = createPath(0.1);
        }

        function onMouseMove(event) {
            var location = path.getNearestLocation(event.point);
            var segment = location.segment;
            var point = segment.point;

            if (!point.fixed && location.distance < size.height / 4) {
                var y = event.point.y;
                point.y += (y - point.y) / 6;
                var previous = segment.previous && segment.previous.point;
                var next = segment.next && segment.next.point;
                if (previous && !previous.fixed)
                    previous.y += (y - previous.y) / 24;
                if (next && !next.fixed)
                    next.y += (y - next.y) / 24;
            }
        }

        function onFrame(event) {
            updateWave(path);
        }

        function updateWave(path) {
            var force = 1 - values.friction * values.timeStep * values.timeStep;
            for (var i = 0, l = path.segments.length; i < l; i++) {
                var point = path.segments[i].point;
                var dy = (point.y - point.py) * force;
                point.py = point.y;
                point.y = Math.max(point.y + dy, 0);
            }

            for (var j = 0, l = springs.length; j < l; j++) {
                springs[j].update();
            }
            path.smooth();
        }

        function onKeyDown(event) {
            if (event.key == 'space') {
                path.fullySelected = !path.fullySelected;
                path.fillColor = path.fullySelected ? null : 'black';
            }
        }
    </script>


    <canvas id="canvas" resize="" hidpi="off" width="1150" height="220" data-paper-scope="1" style="-webkit-user-select: none; touch-action: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></canvas>
      <h1>Welcome to Me!</h1>
  <p><%= link_to "Enter", website_index_path, class: 'btn btn-success' %></p>